{"uid":"a1a13bcf2446b27e","name":"test_attachments","fullName":"tests.test_attachments#test_attachments","historyId":"a5b9628e7aa5b269762a622087644994","time":{"start":1697444619827,"stop":1697444619827,"duration":0},"status":"broken","statusMessage":"ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)","statusTrace":"self = <allure_commons._allure.fixture object at 0x7ff7e6c4aa50>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:21: in browser_management\n    browser.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1204: in quit\n    self.driver.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1099: in driver\n    return self.config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:345: in __get__\n    driver = config.build_driver_strategy(config)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nconfig = <selene.core.configuration.Config object at 0x7ff7e625de90>\n\n    def _build_local_driver_by_name_or_remote_by_url_and_options(\n        config: Config,\n    ) -> WebDriver:\n        from selenium.webdriver import (\n            ChromeOptions,\n            EdgeOptions,\n            Chrome,\n            Firefox,\n            Edge,\n        )\n    \n        from selenium.webdriver.chrome.service import Service as ChromeService\n        from selenium.webdriver.firefox.service import Service as FirefoxService\n        from selenium.webdriver.edge.service import Service as EdgeService  # type: ignore\n    \n        from webdriver_manager.chrome import ChromeDriverManager  # type: ignore\n        from webdriver_manager.firefox import GeckoDriverManager  # type: ignore\n        from webdriver_manager.microsoft import EdgeChromiumDriverManager  # type: ignore\n    \n>       from webdriver_manager.core.utils import ChromeType  # type: ignore\nE       ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:69: ImportError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser_management","time":{"start":1697444619826,"stop":1697444619826,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)","statusTrace":"self = <allure_commons._allure.fixture object at 0x7ff7e6c4aa50>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:21: in browser_management\n    browser.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1204: in quit\n    self.driver.quit()\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1099: in driver\n    return self.config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:345: in __get__\n    driver = config.build_driver_strategy(config)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nconfig = <selene.core.configuration.Config object at 0x7ff7e625de90>\n\n    def _build_local_driver_by_name_or_remote_by_url_and_options(\n        config: Config,\n    ) -> WebDriver:\n        from selenium.webdriver import (\n            ChromeOptions,\n            EdgeOptions,\n            Chrome,\n            Firefox,\n            Edge,\n        )\n    \n        from selenium.webdriver.chrome.service import Service as ChromeService\n        from selenium.webdriver.firefox.service import Service as FirefoxService\n        from selenium.webdriver.edge.service import Service as EdgeService  # type: ignore\n    \n        from webdriver_manager.chrome import ChromeDriverManager  # type: ignore\n        from webdriver_manager.firefox import GeckoDriverManager  # type: ignore\n        from webdriver_manager.microsoft import EdgeChromiumDriverManager  # type: ignore\n    \n>       from webdriver_manager.core.utils import ChromeType  # type: ignore\nE       ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:69: ImportError","steps":[],"attachments":[{"uid":"2c12d2718e98fa97","name":"Text","source":"2c12d2718e98fa97.txt","type":"text/plain","size":12},{"uid":"683e3bcc220cb327","name":"Html","source":"683e3bcc220cb327.html","type":"text/html","size":22},{"uid":"a4c8ea5d3bcdb535","name":"Json","source":"a4c8ea5d3bcdb535.json","type":"application/json","size":25}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"browser_management::0","time":{"start":1697444619827,"stop":1697444619863,"duration":36},"status":"broken","statusMessage":"ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/qa_guru_python_7/qa_guru_python_7/tests/conftest.py\", line 21, in browser_management\n    browser.quit()\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1204, in quit\n    self.driver.quit()\n    ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1099, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 345, in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 69, in _build_local_driver_by_name_or_remote_by_url_and_options\n    from webdriver_manager.core.utils import ChromeType  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_attachments"},{"name":"host","value":"fv-az398-616"},{"name":"thread","value":"2190-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_attachments"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":2,"unknown":0,"total":5},"items":[{"uid":"8669108cd64a95ec","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/9//#testresult/8669108cd64a95ec","status":"passed","time":{"start":1688982498840,"stop":1688982498840,"duration":0}},{"uid":"38aaf52a2b3d5ce4","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/8//#testresult/38aaf52a2b3d5ce4","status":"passed","time":{"start":1688981951137,"stop":1688981951137,"duration":0}},{"uid":"b729944243ffab7e","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/7//#testresult/b729944243ffab7e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55bfc5e0b4e3 <unknown>\n#1 0x55bfc5b3ac76 <unknown>\n#2 0x55bfc5b63d78 <unknown>\n#3 0x55bfc5b60029 <unknown>\n#4 0x55bfc5b9eccc <unknown>\n#5 0x55bfc5b9e47f <unknown>\n#6 0x55bfc5b95de3 <unknown>\n#7 0x55bfc5b6b2dd <unknown>\n#8 0x55bfc5b6c34e <unknown>\n#9 0x55bfc5dcb3e4 <unknown>\n#10 0x55bfc5dcf3d7 <unknown>\n#11 0x55bfc5dd9b20 <unknown>\n#12 0x55bfc5dd0023 <unknown>\n#13 0x55bfc5d9e1aa <unknown>\n#14 0x55bfc5df46b8 <unknown>\n#15 0x55bfc5df4847 <unknown>\n#16 0x55bfc5e04243 <unknown>\n#17 0x7fb395f18b43 <unknown>","time":{"start":1688980168357,"stop":1688980168358,"duration":1}},{"uid":"7e7ae66eccea1768","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/5//#testresult/7e7ae66eccea1768","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x56282ac2a4e3 <unknown>\n#1 0x56282a959c76 <unknown>\n#2 0x56282a982d78 <unknown>\n#3 0x56282a97f029 <unknown>\n#4 0x56282a9bdccc <unknown>\n#5 0x56282a9bd47f <unknown>\n#6 0x56282a9b4de3 <unknown>\n#7 0x56282a98a2dd <unknown>\n#8 0x56282a98b34e <unknown>\n#9 0x56282abea3e4 <unknown>\n#10 0x56282abee3d7 <unknown>\n#11 0x56282abf8b20 <unknown>\n#12 0x56282abef023 <unknown>\n#13 0x56282abbd1aa <unknown>\n#14 0x56282ac136b8 <unknown>\n#15 0x56282ac13847 <unknown>\n#16 0x56282ac23243 <unknown>\n#17 0x7f08f9edab43 <unknown>","time":{"start":1688978993621,"stop":1688978993622,"duration":1}}]},"tags":[]},"source":"a1a13bcf2446b27e.json","parameterValues":[]}